//+build !swipe

// Code generated by Swipe v2.0.0-beta6. DO NOT EDIT.

package transport

import (
	"github.com/go-kit/kit/endpoint"
	"github.com/l-vitaly/go-kit/transport/http/jsonrpc"
)

type httpError struct {
	code    int
	data    interface{}
	message string
}

func (e *httpError) Error() string {
	return e.message
}
func (e *httpError) StatusCode() int {
	return e.code
}
func (e *httpError) ErrorData() interface{} {
	return e.data
}
func (e *httpError) SetErrorData(data interface{}) {
	e.data = data
}
func (e *httpError) SetErrorMessage(message string) {
	e.message = message
}
func ErrorDecode(code int, message string, data interface{}) (err error) {
	switch code {
	default:
		err = &httpError{code: code}
	}
	if err, ok := err.(interface{ SetErrorData(data interface{}) }); ok {
		err.SetErrorData(data)
	}
	if err, ok := err.(interface{ SetErrorMessage(message string) }); ok {
		err.SetErrorMessage(message)
	}
	return
}

func middlewareChain(middlewares []endpoint.Middleware) endpoint.Middleware {
	return func(next endpoint.Endpoint) endpoint.Endpoint {
		if len(middlewares) == 0 {
			return next
		}
		outer := middlewares[0]
		others := middlewares[1:]
		for i := len(others) - 1; i >= 0; i-- {
			next = others[i](next)
		}
		return outer(next)
	}
}
func GenericServerOptions(v ...jsonrpc.ServerOption) ServerOption {
	return func(o *serverOpts) { o.genericServerOption = v }
}

func GenericServerEndpointMiddlewares(v ...endpoint.Middleware) ServerOption {
	return func(o *serverOpts) { o.genericEndpointMiddleware = v }
}

type ServerOption func(*serverOpts)
type serverOpts struct {
	genericServerOption             []jsonrpc.ServerOption
	genericEndpointMiddleware       []endpoint.Middleware
	serviceAddServerOption          []jsonrpc.ServerOption
	serviceAddEndpointMiddleware    []endpoint.Middleware
	serviceDeleteServerOption       []jsonrpc.ServerOption
	serviceDeleteEndpointMiddleware []endpoint.Middleware
	serviceGetServerOption          []jsonrpc.ServerOption
	serviceGetEndpointMiddleware    []endpoint.Middleware
	serviceUpdateServerOption       []jsonrpc.ServerOption
	serviceUpdateEndpointMiddleware []endpoint.Middleware
}

func ServiceAddServerOptions(opt ...jsonrpc.ServerOption) ServerOption {
	return func(c *serverOpts) { c.serviceAddServerOption = opt }
}

func ServiceAddServerEndpointMiddlewares(opt ...endpoint.Middleware) ServerOption {
	return func(c *serverOpts) { c.serviceAddEndpointMiddleware = opt }
}

func ServiceDeleteServerOptions(opt ...jsonrpc.ServerOption) ServerOption {
	return func(c *serverOpts) { c.serviceDeleteServerOption = opt }
}

func ServiceDeleteServerEndpointMiddlewares(opt ...endpoint.Middleware) ServerOption {
	return func(c *serverOpts) { c.serviceDeleteEndpointMiddleware = opt }
}

func ServiceGetServerOptions(opt ...jsonrpc.ServerOption) ServerOption {
	return func(c *serverOpts) { c.serviceGetServerOption = opt }
}

func ServiceGetServerEndpointMiddlewares(opt ...endpoint.Middleware) ServerOption {
	return func(c *serverOpts) { c.serviceGetEndpointMiddleware = opt }
}

func ServiceUpdateServerOptions(opt ...jsonrpc.ServerOption) ServerOption {
	return func(c *serverOpts) { c.serviceUpdateServerOption = opt }
}

func ServiceUpdateServerEndpointMiddlewares(opt ...endpoint.Middleware) ServerOption {
	return func(c *serverOpts) { c.serviceUpdateEndpointMiddleware = opt }
}
